channels:
  - conda-forge
  - nodefaults
dependencies:
  #r dependencies
  - r-base             >=3.6.1,<4
  - r-loader           ==1.7.1
  - r-loader.2nc       ==0.1.1
  - r-transformer      ==2.1.0
  - r-downscaler       ==3.3.2
  - r-visualizer       ==1.6.0
  - r-downscaler.keras ==1.0.0
  - r-climate4r.value  ==0.0.2
  - r-climate4r.udg    ==0.2.4
  - r-value            ==2.2.2
  - r-loader.java      ==1.1.1
  - r-tensorflow       ==2.6.0
  - r-irkernel==1.2
  - r-magrittr     ==2.0.1
  - r-rcolorbrewer ==1.1_2
  - r-gridextra    ==2.3
  - r-ggplot2      ==3.3.3
  - cdo ==1.9.10
  #python dependencies
  - tensorflow         ==2.6.*
  - python             ==3.9.*
