channels:
- conda-forge
- r
dependencies:
# r-base=3.6
- r-rjava
- r-gdalutils
- r-akima
- r-kohonen
- r-earth
- r-latticeextra
- r-spatstat<2
- r-udunits2
- r-mapplots
- r-specsverification
- r-e1071
- r-rcurl
- r-caret
- r-signal
- r-verification
- r-rmarkdown
- r-evd
- r-devtools
- r-geosphere
- r-keras
- r-sampling
- r-lmoments
- r-ncdf4
- r-pbapply
- r-presenceabsence
- r-glmnet
- r-ranger
- r-deepnet
- r-randomforest
- r-splancs
- r-sticky
- r-pcict
- r-padr
- r-gtools
- r-spatstat.linnet<2
- r-tree
- r-vioplot
- r-dismo
